[profile.default]
viaIR = true
optimizer = true
optimizer_runs = 200
[profile.default]
src = 'contracts'
test = 'foundry/test'
out = 'out'
libs = ['lib']
solc_version = '0.8.26'
optimizer = true
optimizer_runs = 200

[fuzz]
runs = 256

[profile.ci]
fuzz.runs = 1024
