name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Foundry (direct download)
        run: |
          set -euo pipefail
          mkdir -p "$HOME/.foundry/bin"
          echo "Downloading foundryup tarball to $HOME/.foundry/bin"
          curl -fsSL "https://github.com/foundry-rs/foundry/releases/latest/download/foundryup-x86_64-unknown-linux-gnu.tar.gz" | tar -xz -C "$HOME/.foundry/bin"
          chmod +x "$HOME/.foundry/bin/foundryup"
          ls -la "$HOME/.foundry/bin" || true
          # Invoke foundryup to install toolchain
          "$HOME/.foundry/bin/foundryup" -y
          # Add foundry binaries to PATH for subsequent steps
          echo "$HOME/.foundry/bin" >> $GITHUB_PATH

      - name: Install npm deps if present
        run: |
          if [ -f package.json ]; then npm ci; fi

      - name: Run Forge tests
        run: forge test --via-ir -v

      - name: Run Slither (Docker)
        run: |
          mkdir -p results
          docker run --rm -v ${{ github.workspace }}:/src -w /src ghcr.io/crytic/slither:latest \
            slither --solc-remaps "@openzeppelin/=node_modules/@openzeppelin/" --json results/slither.json || true

      - name: Upload Slither results
        uses: actions/upload-artifact@v4
        with:
          name: slither-results
          path: results/slither.json
