name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Foundry
        run: |
          # Install Foundry toolchain
          curl -L https://foundry.paradigm.xyz | bash
          # Debug: list homedir and foundry dir (will appear in runner logs)
          ls -la $HOME || true
          ls -la $HOME/.foundry || true
          # Source shell rc to ensure foundryup is on PATH in this step
          source $HOME/.bashrc || true
          # Add foundry binaries to PATH for subsequent steps
          echo "$HOME/.foundry/bin" >> $GITHUB_PATH
          # Prefer direct call if present, otherwise fallback to foundryup if on PATH
          if [ -x "$HOME/.foundry/bin/foundryup" ]; then
            $HOME/.foundry/bin/foundryup -y
          elif command -v foundryup >/dev/null 2>&1; then
            foundryup -y
          else
            echo "foundryup not found after install" >&2
            exit 1
          fi

      - name: Install npm deps if present
        run: |
          if [ -f package.json ]; then npm ci; fi

      - name: Run Forge tests
        run: forge test --via-ir -v

      - name: Run Slither (Docker)
        run: |
          mkdir -p results
          docker run --rm -v ${{ github.workspace }}:/src -w /src ghcr.io/crytic/slither:latest \
            slither --solc-remaps "@openzeppelin/=node_modules/@openzeppelin/" --json results/slither.json || true

      - name: Upload Slither results
        uses: actions/upload-artifact@v4
        with:
          name: slither-results
          path: results/slither.json
